name: Changelog CI
description: A GitHub Action that generates changelog, Then the changelog is committed and/or commented to the release Pull request.
author: Maksudul Haque
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  changelog_filename:
    description: 'Name of the changelog file if not provided defaults to CHANGELOG.md'
    required: false
    default: 'CHANGELOG.md'
  config_file:
    description: 'Location of the config JSON file'
    required: false
  committer_username:
    description: 'Username of that user who will commit'
    required: false
    default: 'changelog'
  committer_email:
    description: 'Email Address of that user who will commit'
    required: false
    default: 'changelog@detalytics.com'
runs:
  using: 'docker'
  image: 'Dockerfile'
